// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNEzZ5dFdElGvBdBRhsGCoK0LMyC1dx8U',
    appId: '1:1046651720228:web:73a2c13ab21e0397ddfeb1',
    messagingSenderId: '1046651720228',
    projectId: 'finalprojectmad-fad74',
    authDomain: 'finalprojectmad-fad74.firebaseapp.com',
    storageBucket: 'finalprojectmad-fad74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH5LRIeIwoyDuMOPR2bCoJ03cJf-5qjqk',
    appId: '1:1046651720228:android:d1859df038ba7c73ddfeb1',
    messagingSenderId: '1046651720228',
    projectId: 'finalprojectmad-fad74',
    storageBucket: 'finalprojectmad-fad74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2IDDn94arezrusPVz9w1_fnjO3Y-1t5Q',
    appId: '1:1046651720228:ios:f2c1c56faec3993fddfeb1',
    messagingSenderId: '1046651720228',
    projectId: 'finalprojectmad-fad74',
    storageBucket: 'finalprojectmad-fad74.appspot.com',
    iosBundleId: 'com.example.pantrychef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2IDDn94arezrusPVz9w1_fnjO3Y-1t5Q',
    appId: '1:1046651720228:ios:f2c1c56faec3993fddfeb1',
    messagingSenderId: '1046651720228',
    projectId: 'finalprojectmad-fad74',
    storageBucket: 'finalprojectmad-fad74.appspot.com',
    iosBundleId: 'com.example.pantrychef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNEzZ5dFdElGvBdBRhsGCoK0LMyC1dx8U',
    appId: '1:1046651720228:web:68de68ed2acb697addfeb1',
    messagingSenderId: '1046651720228',
    projectId: 'finalprojectmad-fad74',
    authDomain: 'finalprojectmad-fad74.firebaseapp.com',
    storageBucket: 'finalprojectmad-fad74.appspot.com',
  );
}
